[project]
name = "ebook-language"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "ebooklib>=0.18",
    "isort>=5.13.2",
    "ruff>=0.7.0",
]
